create table posts_answer
(
    id      bigint generated by default as identity
        primary key,
    date    timestamp,
    head    varchar(1000),
    user_id bigint
        constraint fk5lidm6cqbc7u4xhqpxm898qme
            references users
);

alter table posts_answer
    owner to postgres;